config/routes.rb
Rails.application.routes.draw do
  get "business_trips/index"
  get "calendar/index"
  get "new_staff_schedules/index"
  get "new_schedules/index"
  get "new_reserves/index"
  get "new_reserves/show"
  get "new_reserves/confirm"
  get "new_reserves/new"

  
   #  新レイアウト用
   root "main#top"
   # root "main#top_mente"
   get "about_metatron" => "main#about_metatron"
   get "intestinal" => "main#intestinal"
   get "price_plan" => "main#price_plan"
   get "price_plan_coupon" => "main#price_plan_coupon"
   get "fasting" => "main#fasting"
   get "intestinal" => "main#intestinal"
   get "massage" => "main#massage"
   get "registration_thanks" => "main#registration_thanks"
   get "metatron_sale" => "main#metatron_sale"
   get "staffs" => "main#staffs"
   get 'price_list_select' => 'main#price_list_select'
   get 'price_plan_admin' => 'main#price_plan_admin'

   get "special_treatment_price" => "main#special_treatment_price"

    get 'home/readme' => 'home#readme'
    get 'home/readmust/:id' => 'home#readmust'
    get 'lppage' => 'home#lppage'
    
    
    devise_for :users, :controllers => {
        :registrations => 'users/registrations',
        :sessions => 'users/sessions',
        :passwords => 'users/passwords'
    }
   
#   delete 'users/destroy_user' => 'users#destroy_user'
   resources :users, :only => [:index, :edit, :update, :show, :destroy] do
      get 'schedules/month_select' => 'schedules#month_select'
      # resources :schedules
   end
   # 全userデータバックアップ
   get 'backup_users' => 'users#backup_users'
   get 'users/index/:per' => 'users#index'
   # post 'reservations/make_holiday/:date/:space' => 'reservations#make_holiday'
   # get 'reservations/my_reserved' => 'reservations#my_reserved'
   # get 'reservations/my_reserved_past' => 'reservations#my_reserved_past'
   
   # reservations でアクセスされても新予約画面(reserves#index)へ
   # get 'reservations' => 'reserves#index'
   # resources :reservations
   
   get 'data_conversion' => 'reserves#data_conversion'
   post 'reserves/make_holiday/:date/:start_date/:space' => 'reserves#make_holiday'
   get 'reserves/my_reserved' => 'reserves#my_reserved'
   # 休日の削除
   delete 'reserves/:id/:calender_start_date/holiday' => 'reserves#delete'
   # 予約の削除
   delete 'reserves/:id' => 'reserves#destroy'
   get 'reserves/machine_select' => 'reserves#machine_select'
   get 'reserves/:machine/index' => 'reserves#index'
   get 'reserves/new_cust' => 'reserves#new_cust'
   get 'reserves/new_cust_other' => 'reserves#new_cust_other'
   
   resources :reserves, except: [:show, :destroy]
   
   get 'all_schedules' => 'schedules#all_schedules'
   
   patch "admin/staffs/staff_machine_relations" => "staff_machine_relations#update"

   
   scope :admin do
      post "/staffs/:id" => "staffs#fire"
      resources :staffs do
         resources :schedules
      end
   end
   
   
   scope :admin do
      resources :machines do
         resources :machine_schedules
      end
   end   
   
   patch "staffs/:id/nonactivate" => "staffs#nonactivate"
   patch "staffs/:id/activate" => "staffs#activate"
   
   resources :user_types
   # post 'reservations/confirm' => 'reservations#confirm'
   
   # get 'inquiries/:id/answer' => 'inquiries#answer'
   # get 'inquiries/new' => 'inquiries#new1'
   resources :inquiries do 
      resources :answers, :only => [:new, :create, :show]
   end
   
   resources :metatron_sale_inquiries do 
      resources :ms_inquiry_answers, :only => [:new, :create, :show]
   end   
   
   # get 'answers/:id/new' => 'answers#new'
   # resources :answers, :only => [:create, :show, :index]
   
   resources :pay_types
   

   get 'payments/pay_select' => 'payments#pay_select'
   #　上記工事中にて下記に(2020/2/13)
   # get 'payments/pay_select' => 'payments#construction'

   get 'payments/complete_payment' => 'payments#complete_payment'
   get 'payments/complete_cash_payment' => 'payments#complete_cash_payment'
   get 'payments/:id/new' => 'payments#new'
   delete 'payment_destroy/:id' => 'payments#payment_destroy'
   resources :payments, :only => [:show, :index, :edit, :update, :destroy]
   resources :page_contents
   
#   算命学用
   get 'sanmeis/menu' => 'sanmeis#menu'
   get 'sanmeis/meishiki' => 'sanmeis#meishiki'
   get 'sanmeis/enegry' => 'sanmeis#energy'
   get 'sanmeis/handred_hyou' => 'sanmeis#handred_hyou'
   get 'sanmeis/handred_graph' => 'sanmeis#handred_graph'
   get 'sanmeis/koudo_area' => 'sanmeis#koudo_area' 
   get 'sanmeis/rikushin' => 'sanmeis#rikushin'

   # 新予約システム 2025/08/01
   # ✅ 新予約機能
   resources :new_reserves, except: [:edit, :update] do
      collection do
       post :confirm
      end
   end

   get 'calendar', to: 'calendar#index'
   get 'calendar/availability', to: 'calendar#availability', defaults: { format: :json }

   namespace :admin do
      resources :new_schedules, only: [:index, :create, :update, :destroy]
      resources :new_reserves, only: [:index, :show, :destroy]
      # 出張登録管理
      resources :business_trips, only: [:index, :create, :destroy] do
         collection do
         patch :bulk_update
         end
      end 
   end

     # スタッフスケジュール管理
   resources :new_staff_schedules, only: [:index, :show, :update] do
      collection do
      patch :bulk_update
      end
   end

   # 旧パスから新パスへのリダイレクト
   get 'staff_schedules', to: redirect('/new_staff_schedules')

    

   

   
   
   resources :meishikis, only: [:new, :create, :index, :show, :destroy]

   get '*anything' => 'errors#routing_error'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/staff.rb
class Staff < ApplicationRecord
    # belongs_to :user
    has_many :reserves
    has_many :staff_machine_relations
    accepts_nested_attributes_for :staff_machine_relations
    has_many :schedules
    
      validates :name, presence: true
      validates :name_kanji, presence: true
      
    def staff_machines
      self.staff_machine_relations.pluck(:machine).join(',')
    end

      
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  
  layout 'main/main'
  
  before_action :authenticate_staff_user?
  
  def activate
    @staff = Staff.find(params[:id])
    @staff.update(active_flag: true)
    redirect_to staff_schedules_path(@staff)
  end
  
  def nonactivate
    @staff = Staff.find(params[:id])
    @staff.update(active_flag: false)    
    redirect_to staff_schedules_path(@staff)
  end
  
  def new
    # user.id = 0 は休みなので選択からはずす　　user_type 1:管理者  10:施術者
    @already_staffs = Staff.all.pluck(:user_id)
    @already_staffs =  @already_staffs + [1144,1145]
    @users = User.where.not(id: 0).where(user_type: ["1","10"]).where.not(id: @already_staffs).pluck(:id, :name)
    @staff = Staff.new
    registored_staff_array = StaffMachineRelation.where.not(id: 0).where.not(staff_id: 0).select(:staff_id).distinct.pluck(:staff_id)
    @staffs = Staff.where(id: registored_staff_array)
    @staff_machine_relations = StaffMachineRelation.where.not(staff_id: 0).order(:id)
    @staff_machine_relation = @staff.staff_machine_relations.build
  end
  
  
  def create
    
    logger.debug("============================== staff_params  = #{staff_params}}")
    logger.debug("============================== staff_params machine = #{params[:staff][:staff_machine_relations_attributes]["0"][:machine]}}")
    
    @staff = Staff.new(staff_params)
    
    if @staff.save
      flash[:notice] = "#{@staff.name}のスタッフ登録を完了しました"
      redirect_to "/admin/staffs"
    else
      # render :new
      flash[:notice] = "スタッフ登録できませんでした"
      redirect_to new_staff_path
    end
  end
  
  
  def index
    # 指名なし0でもない 解任(dismiss_flug: true)もされていない
    @staffs = Staff.where.not(id: 0, dismiss_flag: true).order(:id)
  end
  
  
  def destroy
    @staff = Staff.find(params[:id])
    logger.debug("解任対象staff= #{@staff.name}")
    @schedules = @staff.schedules
    @staff_machine_relations = @staff.staff_machine_relations
    logger.debug("^^^^^^^ @staff_machine_relation count= #{@staff_machine_relations.count}")
    @schedules.destroy_all
    @staff_machine_relations.destroy_all
    # reserve情報にstaff_idがあるので、物理削除せずに解任フラグをtrueにする
    if @staff.update(dismiss_flag: true)
     flash[:notice] = "スタッフ解任しました"
     redirect_to "/admin/staffs"
   else
     flash[:alert] = "スタッフ解任できませんでした"
     redirect_back(fallback_location: root_path)
   end
  end
  
  def update
    @staff = Staff.find(params[:id])
    logger.debug("就任対象staff= #{@staff.name}")
    if @staff.update(dismiss_flag: false)
     flash[:notice] = "再度スタッフ就任しました"
     redirect_to "/admin/staffs"      
    else
     flash[:alert] = "スタッフ就任できませんでした"
     redirect_back(fallback_location: root_path)      
    end
  end
  
  def fire 
    @staff = Staff.find(params[:id])
    if @staff.destroy
      flash[:notice] = "スタッフ完全解雇しました"
      redirect_to "/admin/staffs"      
    else
      flash[:alert] = "スタッフ解雇できませんでした"
      redirect_back(fallback_location: root_path)      
    end
  end
  
  
  private 
    def staff_params
      params.require(:staff).permit(:name, :name_kanji, :user_id, staff_machine_relations_attributes: [:machine])
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/index.html.erb
<div id="staff-index">
    <h3>出勤カレンダー入力・変更</h3>
    <% if user_signed_in? && current_user.user_type == "1" %>
      <%= link_to "スタッフ登録・変更", new_staff_path, class: "btn btn-primary" %><br>
    <% end %>
    <%= link_to "全スケジュール確認", all_schedules_path, class: "all-schedules" %>
    
    <ul class="staff-ul">
      <% if current_user.user_type == "1" %>
        <% @staffs.each do |staff| %>
            <% if staff.dismiss_flag == false %>
               <li><%= link_to staff.name, staff_schedules_path(staff) %></li>
            <% else %>
               <li><%= link_to staff.name, staff_schedules_path(staff), class: "dismissal-link" %></li>
            <% end %>
        <% end %>
      <% elsif current_user.user_type == "10" && Staff.find_by(user_id: current_user.id) %>
        <li><%= link_to Staff.find_by(user_id: current_user.id).name, staff_schedules_path(Staff.find_by(user_id: current_user.id)) %></li>
      <% else %>
        <li>スタッフ登録処理未完了です</li>
      <% end %>
    </ul>
</div>

<style>
  #staff-index .all-schedules {
    font-size: 18px;
    margin-bottom: 10px;
    color: green;
  }
  
  .dismissal-link {
    color: red;
    /*margin-left: 50px;*/
  }
  
  @media (max-width: 414px) {
      #staff-index .all-schedules {
        font-size: 15px;
      }
  }
</style>

app/views/staffs/index_staff_machine.html.erb
<div id="staff-index">
    <h3>出勤カレンダー入力・変更</h3>
    <%= link_to "機械登録", new_staff_path, class: "btn btn-primary" %>
    <ul class="staff-ul">
        <% @staffs.each do |staff| %>
             <li><%= link_to User.find(staff.user_id).name, user_schedules_path(staff.user_id) %></li>
        <% end %>
    </ul>
</div>

app/views/staffs/new.html.erb
<div id="staff-new">
    <h4>スタッフ登録</h4>
        <% hash = {Holistic: "h", Wellbeing: "w", "その他": "o"} %>
        <%= form_with model: @staff, url: "/admin/staffs" do |f| %>
          <div>スタッフ名：<%= f.text_field :name, required: true, class: "form-control staff-input-width" %></div>
          <div>スタッフ名漢字：<%= f.text_field :name_kanji, class: "form-control staff-input-width" %></div><br>
          <div>
              <% @users.each do |key, value| %>
                <span style="display: inline-block; padding-right: 10px;"><%= f.radio_button :user_id, key %><%= value %></span>
              <% end %>

            <!--<ul style="text-align: left;">-->
            <!--  < @users.each do |key, value| %>-->
            <!--    <li style="list-style: none;"><= f.check_box :user_id, {checked: false, multiple: true}, key, nil %><= value %></li>-->
            <!--  < end %>-->
            <!--</ul>-->
          </div>
          <div>内容：
            <%= f.fields_for :staff_machine_relations do |smr| %>
                <div class="checkbox">
                  <%= smr.radio_button :machine, "h", checked: true %>Holistic　
                  <%= smr.radio_button :machine, "w" %>Wellbeing　
                  <!--<= smr.radio_button :machine, "s" %>算命学　-->
                  <br class="machine-select-br">
                  <%= smr.radio_button :machine, "e" %>エステ　
                  <%= smr.radio_button :machine, "b" %>鍼・整体　
                  <%= smr.radio_button :machine, "o" %>その他
                </div>
            <% end %>
          </div>
          <div><%= f.submit "登録", class: "btn btn-primary" %></div>
        <% end %>
<hr>        
</div>

<div id="staff-edit">
   <h4>担当マシン修正</h4>
        <% hash = {Holistic: "h", Wellbeing: "w", "その他": "o"} %>

        <%= form_with model: @staff_machine_relation, url: admin_staffs_staff_machine_relations_path, method: :patch do |g| %>
          <ul style="list-style: none; padding-left: 0;">
            <% @staffs.each do |staff| %>
                   <li>
                     <%= g.radio_button :staff_id, staff.id %>
                     <label style="font-weight: normal; display: inline-block;"><%= "#{staff.name}..#{staff.staff_machines}" %></label>
                     <!--<= g.label "#{staff.name}..#{staff.staff_machines}", {value: staff.id, style: "font-weight: normal; display: inline-block;"} %>-->
                   </li>
                   
            <% end %>
          </ul>
          <div>※ 使用するマシンは全てチェックを。&#8595;
            <!--<= g.fields_for :staff_machine_relations do |smr| %>-->
                <div class="checkbox">
                  <%= g.collection_check_boxes :machine, Machine.all, :short_word, :name, include_hidden: false %><br>
                </div>
            <!--< end %>-->
          </div>
          <div><%= g.submit "修正", class: "btn btn-success" %></div>
        <% end %>  
</div>

app/views/staffs/new_staff_machine.html.erb
<div id="staff-new">
    <h2>機械登録</h2>
    <% if @users.present? %>
        <%= form_for @staff do |f| %>
          <div>
              <% @users.each do |user| %>
                  <div class="radio-inline">
                    <%= f.radio_button :user_id, user.id %>
                    <%= f.label user.name, class: "job_type_label" %>
                  </div>
              <% end %>
          </div>
          <%= f.submit "登録", class: "btn btn-primary" %>
        <% end %>
    <% else %>
      <p>登録すべき機械がありません</p>
    <% end %>
</div>