config/routes.rb
Rails.application.routes.draw do
  get "business_trips/index"
  get "calendar/index"
  get "new_staff_schedules/index"
  get "new_schedules/index"
  get "new_reserves/index"
  get "new_reserves/show"
  get "new_reserves/confirm"
  get "new_reserves/new"

  
   #  新レイアウト用
   root "main#top"
   # root "main#top_mente"
   get "about_metatron" => "main#about_metatron"
   get "intestinal" => "main#intestinal"
   get "price_plan" => "main#price_plan"
   get "price_plan_coupon" => "main#price_plan_coupon"
   get "fasting" => "main#fasting"
   get "intestinal" => "main#intestinal"
   get "massage" => "main#massage"
   get "registration_thanks" => "main#registration_thanks"
   get "metatron_sale" => "main#metatron_sale"
   get "staffs" => "main#staffs"
   get 'price_list_select' => 'main#price_list_select'
   get 'price_plan_admin' => 'main#price_plan_admin'

   get "special_treatment_price" => "main#special_treatment_price"

    get 'home/readme' => 'home#readme'
    get 'home/readmust/:id' => 'home#readmust'
    get 'lppage' => 'home#lppage'
    
    
    devise_for :users, :controllers => {
        :registrations => 'users/registrations',
        :sessions => 'users/sessions',
        :passwords => 'users/passwords'
    }
   
#   delete 'users/destroy_user' => 'users#destroy_user'
   resources :users, :only => [:index, :edit, :update, :show, :destroy] do
      get 'schedules/month_select' => 'schedules#month_select'
      # resources :schedules
   end
   # 全userデータバックアップ
   get 'backup_users' => 'users#backup_users'
   get 'users/index/:per' => 'users#index'
   # post 'reservations/make_holiday/:date/:space' => 'reservations#make_holiday'
   # get 'reservations/my_reserved' => 'reservations#my_reserved'
   # get 'reservations/my_reserved_past' => 'reservations#my_reserved_past'
   
   # reservations でアクセスされても新予約画面(reserves#index)へ
   # get 'reservations' => 'reserves#index'
   # resources :reservations
   
   get 'data_conversion' => 'reserves#data_conversion'
   post 'reserves/make_holiday/:date/:start_date/:space' => 'reserves#make_holiday'
   get 'reserves/my_reserved' => 'reserves#my_reserved'
   # 休日の削除
   delete 'reserves/:id/:calender_start_date/holiday' => 'reserves#delete'
   # 予約の削除
   delete 'reserves/:id' => 'reserves#destroy'
   get 'reserves/machine_select' => 'reserves#machine_select'
   get 'reserves/:machine/index' => 'reserves#index'
   get 'reserves/new_cust' => 'reserves#new_cust'
   get 'reserves/new_cust_other' => 'reserves#new_cust_other'
   
   resources :reserves, except: [:show, :destroy]
   
   get 'all_schedules' => 'schedules#all_schedules'
   
   patch "admin/staffs/staff_machine_relations" => "staff_machine_relations#update"

   
   scope :admin do
      post "/staffs/:id" => "staffs#fire"
      resources :staffs do
         resources :schedules
      end
   end
   
   
   scope :admin do
      resources :machines do
         resources :machine_schedules
      end
   end   
   
   patch "staffs/:id/nonactivate" => "staffs#nonactivate"
   patch "staffs/:id/activate" => "staffs#activate"
   
   resources :user_types
   # post 'reservations/confirm' => 'reservations#confirm'
   
   # get 'inquiries/:id/answer' => 'inquiries#answer'
   # get 'inquiries/new' => 'inquiries#new1'
   resources :inquiries do 
      resources :answers, :only => [:new, :create, :show]
   end
   
   resources :metatron_sale_inquiries do 
      resources :ms_inquiry_answers, :only => [:new, :create, :show]
   end   
   
   # get 'answers/:id/new' => 'answers#new'
   # resources :answers, :only => [:create, :show, :index]
   
   resources :pay_types
   

   get 'payments/pay_select' => 'payments#pay_select'
   #　上記工事中にて下記に(2020/2/13)
   # get 'payments/pay_select' => 'payments#construction'

   get 'payments/complete_payment' => 'payments#complete_payment'
   get 'payments/complete_cash_payment' => 'payments#complete_cash_payment'
   get 'payments/:id/new' => 'payments#new'
   delete 'payment_destroy/:id' => 'payments#payment_destroy'
   resources :payments, :only => [:show, :index, :edit, :update, :destroy]
   resources :page_contents
   
#   算命学用
   get 'sanmeis/menu' => 'sanmeis#menu'
   get 'sanmeis/meishiki' => 'sanmeis#meishiki'
   get 'sanmeis/enegry' => 'sanmeis#energy'
   get 'sanmeis/handred_hyou' => 'sanmeis#handred_hyou'
   get 'sanmeis/handred_graph' => 'sanmeis#handred_graph'
   get 'sanmeis/koudo_area' => 'sanmeis#koudo_area' 
   get 'sanmeis/rikushin' => 'sanmeis#rikushin'

   # 新予約システム 2025/08/01
   # ✅ 新予約機能
   resources :new_reserves, except: [:edit, :update] do
      collection do
       post :confirm
      end
   end

   get 'calendar', to: 'calendar#index'
   get 'calendar/availability', to: 'calendar#availability', defaults: { format: :json }

   namespace :admin do
      resources :new_schedules, only: [:index, :create, :update, :destroy]
      resources :new_reserves, only: [:index, :show, :destroy]
      # 出張登録管理
      resources :business_trips, only: [:index, :create, :destroy] do
         collection do
         patch :bulk_update
         end
      end 
   end

     # スタッフスケジュール管理
   resources :new_staff_schedules, only: [:index, :show, :update] do
      collection do
      patch :bulk_update
      end
   end

   # 旧パスから新パスへのリダイレクト
   get 'staff_schedules', to: redirect('/new_staff_schedules')

    

   

   
   
   resources :meishikis, only: [:new, :create, :index, :show, :destroy]

   get '*anything' => 'errors#routing_error'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/new_reserve.rb
class NewReserve < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :new_staff, class_name: 'NewStaff', foreign_key: :new_staff_id
  
    enum :customer_gender, { customer_male: 0, customer_female: 1, customer_other: 2 }
    enum :duration, { thirty_minutes: 1, sixty_minutes: 2 }
  
    validates :date, :start_time_slot, :duration, presence: true
    validates :start_time_slot, inclusion: { in: 0..24 }
    validate :date_cannot_be_in_the_past
  
    # user未登録の場合は顧客情報が必須
    validates :customer_name, :customer_gender, :customer_tel, presence: true, if: -> { user.nil? }
  
    scope :for_date, ->(date) { where(date: date) }
    scope :for_time_slot, ->(time_slot) { where(start_time_slot: time_slot) }
    scope :overlapping, ->(start_slot, duration) {
      where(
        "(start_time_slot <= ? AND start_time_slot + duration - 1 >= ?) OR " \
        "(start_time_slot <= ? AND start_time_slot + duration - 1 >= ?)",
        start_slot, start_slot,
        start_slot + duration - 1, start_slot + duration - 1
      )
    }
  
    def end_time_slot
      duration_value = case duration
                      when 'thirty_minutes'
                        1
                      when 'sixty_minutes'
                        2
                      else
                        duration.to_i
                      end
      start_time_slot + duration_value - 1
    end
  
    def time_slots
      (start_time_slot..end_time_slot).to_a
    end
  
    def customer_display_name
      user&.name || customer_name
    end
  
    def customer_display_gender
      user&.gender || customer_gender
    end
  
    def customer_display_tel
      user&.tel || customer_tel
    end
  
    private
  
    def date_cannot_be_in_the_past
      if date.present? && date < Date.tomorrow
        errors.add(:date, "は明日以降の日付を選択してください")
      end
    end
  end
  

app/controllers/admin/new_reserves_controller.rb
class Admin::NewReservesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @new_reserves = NewReserve.includes(:user, :new_staff)
                              .order(date: :asc, start_time_slot: :asc)
  end

  def show
    @new_reserve = NewReserve.find(params[:id])
  end

  def destroy
    @new_reserve = NewReserve.find(params[:id])
    @new_reserve.destroy
    redirect_to admin_new_reserves_path, notice: '予約を削除しました。'
  end
end

app/controllers/new_reserves_controller.rb
class NewReservesController < ApplicationController
  before_action :set_new_reserve, only: [:show, :destroy]
  before_action :authenticate_user!, only: [:index, :show]

  def index
    @new_reserves = current_user.new_reserves.includes(:new_staff).order(date: :desc, start_time_slot: :asc)
  end

  def show
  end

  def new
    @date = params[:date]&.to_date || Date.tomorrow
    @time_slot = params[:time_slot]&.to_i || 0

    if @date < Date.tomorrow
      redirect_to calendar_path, alert: '過去の日付は予約できません。'
      return
    end

    availability = calculate_slot_availability(@date, @time_slot)

    if availability[:status] == 'unavailable'
      redirect_to calendar_path(date: @date), alert: 'この時間帯は予約できません。'
      return
    end

    @new_reserve = NewReserve.new(date: @date, start_time_slot: @time_slot)
    @available_staff = get_available_staff(@date, @time_slot)
    @time_display = NewSchedule.time_slot_to_time(@time_slot)
  end

  def confirm
    Rails.logger.info "Confirm params: #{new_reserve_params.inspect}"
    @new_reserve = NewReserve.new(new_reserve_params)
    @new_reserve.user = current_user if user_signed_in?
    Rails.logger.info "User signed in: #{user_signed_in?}"
    Rails.logger.info "New reserve valid: #{@new_reserve.valid?}"
    Rails.logger.info "New reserve errors: #{@new_reserve.errors.full_messages}" unless @new_reserve.valid?

    if @new_reserve.date < Date.tomorrow
      redirect_to calendar_path, alert: '過去の日付は予約できません。'
      return
    end

    if @new_reserve.date == Date.tomorrow && Time.current.hour >= 15
      redirect_to calendar_path, alert: '翌日の予約は前日の15時までです。'
      return
    end

    unless @new_reserve.valid?
      @available_staff = get_available_staff(@new_reserve.date, @new_reserve.start_time_slot)
      @time_display = NewSchedule.time_slot_to_time(@new_reserve.start_time_slot)
      @date = @new_reserve.date
      @time_slot = @new_reserve.start_time_slot
      render :new and return
    end

    duration_value = @new_reserve.duration == "thirty_minutes" ? 1 : 2
    unless duration_value == 1 || can_reserve_sixty_minutes?(@new_reserve.date, @new_reserve.start_time_slot, @new_reserve.new_staff_id)
      redirect_to calendar_path(date: @new_reserve.date), alert: 'この枠は60分の予約ができません。'
      return
    end

    availability = calculate_slot_availability(@new_reserve.date, @new_reserve.start_time_slot, duration_value)

    if availability[:status] == 'unavailable'
      redirect_to calendar_path(date: @new_reserve.date), alert: 'この時間帯は既に予約が埋まっています。'
      return
    end

    @staff = NewStaff.find(@new_reserve.new_staff_id)
    @time_display = NewSchedule.time_slot_to_time(@new_reserve.start_time_slot)
  end

  def create
    @new_reserve = NewReserve.new(new_reserve_params)
    @new_reserve.user = current_user if user_signed_in?

    if @new_reserve.date < Date.tomorrow
      redirect_to calendar_path, alert: '過去の日付は予約できません。'
      return
    end

    if @new_reserve.date == Date.tomorrow && Time.current.hour >= 15
      redirect_to calendar_path, alert: '翌日の予約は前日の15時までです。'
      return
    end

    duration_value = @new_reserve.duration == "thirty_minutes" ? 1 : 2

    unless staff_available?(@new_reserve.new_staff_id, @new_reserve.date, @new_reserve.start_time_slot, duration_value)
      redirect_to calendar_path(date: @new_reserve.date), alert: 'スタッフが既に予約されています。'
      return
    end

    availability = calculate_slot_availability(@new_reserve.date, @new_reserve.start_time_slot, duration_value)

    if availability[:status] == 'unavailable'
      redirect_to calendar_path(date: @new_reserve.date), alert: '予約が埋まっています。'
      return
    end

    if @new_reserve.save
      redirect_to calendar_path(date: @new_reserve.date), notice: '予約が完了しました。'
    else
      @available_staff = get_available_staff(@new_reserve.date, @new_reserve.start_time_slot)
      @time_display = NewSchedule.time_slot_to_time(@new_reserve.start_time_slot)
      @date = @new_reserve.date
      @time_slot = @new_reserve.start_time_slot
      render :new
    end
  end

  def destroy
    if @new_reserve.user == current_user || (current_user&.admin?)
      @new_reserve.destroy
      redirect_to new_reserves_path, notice: '予約をキャンセルしました。'
    else
      redirect_to new_reserves_path, alert: '予約をキャンセルする権限がありません。'
    end
  end

  private

  def set_new_reserve
    @new_reserve = NewReserve.find(params[:id])
  end

  def new_reserve_params
    params.require(:new_reserve).permit(
      :date, :start_time_slot, :duration, :new_staff_id, :notes,
      :customer_name, :customer_gender, :customer_tel
    )
  end

  def get_available_staff(date, time_slot)
    working_staff = NewStaff.joins(:new_schedules)
      .where(new_schedules: { date: date, time_slot: time_slot, working: true })
      .where(active: true)

    reserved_staff_ids = NewReserve.where(date: date)
      .where('(start_time_slot <= ? AND start_time_slot + duration - 1 >= ?)', time_slot, time_slot)
      .pluck(:new_staff_id)

    working_staff.where.not(id: reserved_staff_ids)
  end

  def calculate_slot_availability(date, time_slot, duration = 1)
    machine = NewMachine.find_by(name: 'holistic')

    (0...duration).each do |offset|
      slot = time_slot + offset
      return { status: 'unavailable' } if machine.available_count_at(date, slot) <= 0
    end

    available_staff = get_available_staff(date, time_slot)
    count = available_staff.count

    if count >= 2
      { status: 'excellent', available_staff: count }
    elsif count == 1
      { status: 'good', available_staff: count }
    else
      { status: 'unavailable', available_staff: 0 }
    end
  end

  def staff_available?(staff_id, date, start_slot, duration)
    NewReserve.where(new_staff_id: staff_id, date: date)
      .where('(start_time_slot <= ? AND start_time_slot + duration - 1 >= ?)', start_slot, start_slot)
      .or(
        NewReserve.where(new_staff_id: staff_id, date: date)
        .where('(start_time_slot <= ? AND start_time_slot + duration - 1 >= ?)', start_slot + duration - 1, start_slot + duration - 1)
      )
      .none?
  end

  def can_reserve_sixty_minutes?(date, start_time_slot, staff_id)
    return false if start_time_slot + 1 > 24
    s1 = NewSchedule.exists?(new_staff_id: staff_id, date: date, time_slot: start_time_slot, working: true)
    s2 = NewSchedule.exists?(new_staff_id: staff_id, date: date, time_slot: start_time_slot + 1, working: true)
    return false unless s1 && s2

    machine = NewMachine.find_by(name: 'holistic')
    return false unless machine

    return false if machine.available_count_at(date, start_time_slot) == 0
    return false if machine.available_count_at(date, start_time_slot + 1) == 0

    staff_available?(staff_id, date, start_time_slot, 2)
  end
end

app/helpers/admin/new_reserves_helper.rb
module Admin::NewReservesHelper
end

app/helpers/new_reserves_helper.rb
module NewReservesHelper
end

app/views/admin/new_reserves/index.html.erb
<div class="admin-new-reserves container mt-4">
  <div class="row">
    <div class="col-12">
      <h4 class="mb-4">新規予約一覧</h4>
      
      <% if @new_reserves.any? %>
        <div class="table-wrapper">
          <!-- 固定ヘッダー -->
          <div class="table-header">
            <table class="table table-bordered" style="margin-bottom: 0;">
              <thead>
                <tr>
                  <th>予約日時</th>
                  <th>指名スタッフ</th>
                  <th>備考</th>
                  <th>予約者</th>
                  <th>削除</th>
                </tr>
              </thead>
            </table>
          </div>
          
          <!-- スクロール可能なボディ -->
          <div class="table-body">
            <table class="table table-bordered table-striped table-hover" style="margin-bottom: 0;">
              <tbody>
                <% @new_reserves.each do |reserve| %>
                  <tr>
                    <td>
                      <%= reserve.date.strftime('%Y年%m月%d日') %>
                      <small class="text-muted d-block">
                        (<%= %w[日 月 火 水 木 金 土][reserve.date.wday] %>)
                      </small>
                      <div class="mt-1">
                        <%= NewSchedule.time_slot_to_time(reserve.start_time_slot) %>〜
                        <% case reserve.duration %>
                        <% when 'thirty_minutes', 1 %>
                          <small class="badge bg-success ms-1">30分</small>
                        <% when 'sixty_minutes', 2 %>
                          <small class="badge bg-primary ms-1">60分</small>
                        <% end %>
                      </div>
                    </td>
                    <td>
                      <strong><%= reserve.new_staff.name %></strong>
                    </td>
                    <td>
                      <% if reserve.notes.present? %>
                        <%= simple_format(h(reserve.notes), {}, wrapper_tag: "div", class: "mb-0") %>
                      <% else %>
                        <span class="text-muted">-</span>
                      <% end %>
                    </td>
                    <td>
                      <strong><%= reserve.customer_display_name %></strong>
                      <div class="small text-muted">
                        <%= reserve.customer_display_tel %>
                      </div>
                      <div class="mt-1">
                        <% if reserve.user %>
                          <small class="badge bg-primary">会員</small>
                        <% else %>
                          <small class="badge bg-secondary">非会員</small>
                        <% end %>
                        <% case reserve.customer_display_gender %>
                        <% when 'male', 'customer_male' %>
                          <small class="badge bg-info">男性</small>
                        <% when 'female', 'customer_female' %>
                          <small class="badge bg-warning">女性</small>
                        <% else %>
                          <small class="badge bg-secondary">その他</small>
                        <% end %>
                      </div>
                    </td>
                    <td>
                      <%= link_to '削除', admin_new_reserve_path(reserve), 
                          method: :delete,
                          class: 'btn btn-sm btn-secondary',
                          data: { confirm: '本当に削除しますか？' } %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        
        <div class="mt-3">
          <p class="text-muted">
            <i class="fas fa-info-circle"></i>
            合計 <%= @new_reserves.count %> 件の予約があります
          </p>
        </div>
        
      <% else %>
        <div class="alert alert-info text-center">
          <i class="fas fa-calendar-times fa-3x mb-3"></i>
          <h4>予約がありません</h4>
          <p class="mb-0">現在、新規予約はありません。</p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/new_reserves/show.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h3 class="card-title mb-0">
            <i class="fas fa-calendar-check"></i>
            予約詳細
          </h3>
        </div>
        <div class="card-body">
          <div class="row mb-3">
            <div class="col-sm-4">
              <strong>予約日:</strong>
            </div>
            <div class="col-sm-8">
              <%= @new_reserve.date.strftime('%Y年%m月%d日') %>
              (<%= %w[日 月 火 水 木 金 土][@new_reserve.date.wday] %>曜日)
            </div>
          </div>
          
          <div class="row mb-3">
            <div class="col-sm-4">
              <strong>時間:</strong>
            </div>
            <div class="col-sm-8">
              <%= "#{@new_reserve.start_time_slot}:00" %> 〜 
              <%= "#{@new_reserve.end_time_slot + 1}:00" %>
            </div>
          </div>
          
          <div class="row mb-3">
            <div class="col-sm-4">
              <strong>お客様名:</strong>
            </div>
            <div class="col-sm-8">
              <%= @new_reserve.customer_display_name %>
              <% if @new_reserve.user %>
                <span class="badge bg-primary ms-2">会員</span>
              <% else %>
                <span class="badge bg-secondary ms-2">非会員</span>
              <% end %>
            </div>
          </div>
          
          <div class="row mb-3">
            <div class="col-sm-4">
              <strong>性別:</strong>
            </div>
            <div class="col-sm-8">
              <% case @new_reserve.customer_display_gender %>
              <% when 'male', 'customer_male' %>
                <span class="badge bg-info">男性</span>
              <% when 'female', 'customer_female' %>
                <span class="badge bg-warning">女性</span>
              <% else %>
                <span class="badge bg-secondary">その他</span>
              <% end %>
            </div>
          </div>
          
          <div class="row mb-3">
            <div class="col-sm-4">
              <strong>電話番号:</strong>
            </div>
            <div class="col-sm-8">
              <%= @new_reserve.customer_display_tel %>
            </div>
          </div>
          
          <div class="row mb-3">
            <div class="col-sm-4">
              <strong>担当スタッフ:</strong>
            </div>
            <div class="col-sm-8">
              <%= @new_reserve.new_staff.name %>
            </div>
          </div>
          
          <div class="row mb-3">
            <div class="col-sm-4">
              <strong>施術時間:</strong>
            </div>
            <div class="col-sm-8">
              <% case @new_reserve.duration %>
              <% when 'thirty_minutes', 1 %>
                <span class="badge bg-success">30分</span>
              <% when 'sixty_minutes', 2 %>
                <span class="badge bg-primary">60分</span>
              <% end %>
            </div>
          </div>
          
          <% if @new_reserve.user %>
            <div class="row mb-3">
              <div class="col-sm-4">
                <strong>会員情報:</strong>
              </div>
              <div class="col-sm-8">
                <p class="mb-1">ID: <%= @new_reserve.user.id %></p>
                <p class="mb-0">メール: <%= @new_reserve.user.email %></p>
              </div>
            </div>
          <% end %>
        </div>
        
        <div class="card-footer">
          <div class="d-flex justify-content-between">
            <%= link_to '一覧に戻る', admin_new_reserves_path, 
                class: 'btn btn-secondary' %>
            <div>
              <%= link_to '削除', admin_new_reserve_path(@new_reserve), 
                  method: :delete,
                  class: 'btn btn-danger',
                  confirm: '本当に削除しますか？' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>