config/routes.rb
Rails.application.routes.draw do
  get "business_trips/index"
  get "calendar/index"
  get "new_staff_schedules/index"
  get "new_schedules/index"
  get "new_reserves/index"
  get "new_reserves/show"
  get "new_reserves/confirm"
  get "new_reserves/new"

  
   #  新レイアウト用
   root "main#top"
   # root "main#top_mente"
   get "about_metatron" => "main#about_metatron"
   get "intestinal" => "main#intestinal"
   get "price_plan" => "main#price_plan"
   get "price_plan_coupon" => "main#price_plan_coupon"
   get "fasting" => "main#fasting"
   get "intestinal" => "main#intestinal"
   get "massage" => "main#massage"
   get "registration_thanks" => "main#registration_thanks"
   get "metatron_sale" => "main#metatron_sale"
   get "staffs" => "main#staffs"
   get 'price_list_select' => 'main#price_list_select'
   get 'price_plan_admin' => 'main#price_plan_admin'

   get "special_treatment_price" => "main#special_treatment_price"

    get 'home/readme' => 'home#readme'
    get 'home/readmust/:id' => 'home#readmust'
    get 'lppage' => 'home#lppage'
    
    
    devise_for :users, :controllers => {
        :registrations => 'users/registrations',
        :sessions => 'users/sessions',
        :passwords => 'users/passwords'
    }
   
#   delete 'users/destroy_user' => 'users#destroy_user'
   resources :users, :only => [:index, :edit, :update, :show, :destroy] do
      get 'schedules/month_select' => 'schedules#month_select'
      # resources :schedules
   end
   # 全userデータバックアップ
   get 'backup_users' => 'users#backup_users'
   get 'users/index/:per' => 'users#index'
   # post 'reservations/make_holiday/:date/:space' => 'reservations#make_holiday'
   # get 'reservations/my_reserved' => 'reservations#my_reserved'
   # get 'reservations/my_reserved_past' => 'reservations#my_reserved_past'
   
   # reservations でアクセスされても新予約画面(reserves#index)へ
   # get 'reservations' => 'reserves#index'
   # resources :reservations
   
   get 'data_conversion' => 'reserves#data_conversion'
   post 'reserves/make_holiday/:date/:start_date/:space' => 'reserves#make_holiday'
   get 'reserves/my_reserved' => 'reserves#my_reserved'
   # 休日の削除
   delete 'reserves/:id/:calender_start_date/holiday' => 'reserves#delete'
   # 予約の削除
   delete 'reserves/:id' => 'reserves#destroy'
   get 'reserves/machine_select' => 'reserves#machine_select'
   get 'reserves/:machine/index' => 'reserves#index'
   get 'reserves/new_cust' => 'reserves#new_cust'
   get 'reserves/new_cust_other' => 'reserves#new_cust_other'
   
   resources :reserves, except: [:show, :destroy]
   
   get 'all_schedules' => 'schedules#all_schedules'
   
   patch "admin/staffs/staff_machine_relations" => "staff_machine_relations#update"

   
   scope :admin do
      post "/staffs/:id" => "staffs#fire"
      resources :staffs do
         resources :schedules
      end
   end
   
   
   scope :admin do
      resources :machines do
         resources :machine_schedules
      end
   end   
   
   patch "staffs/:id/nonactivate" => "staffs#nonactivate"
   patch "staffs/:id/activate" => "staffs#activate"
   
   resources :user_types
   # post 'reservations/confirm' => 'reservations#confirm'
   
   # get 'inquiries/:id/answer' => 'inquiries#answer'
   # get 'inquiries/new' => 'inquiries#new1'
   resources :inquiries do 
      resources :answers, :only => [:new, :create, :show]
   end
   
   resources :metatron_sale_inquiries do 
      resources :ms_inquiry_answers, :only => [:new, :create, :show]
   end   
   
   # get 'answers/:id/new' => 'answers#new'
   # resources :answers, :only => [:create, :show, :index]
   
   resources :pay_types
   

   get 'payments/pay_select' => 'payments#pay_select'
   #　上記工事中にて下記に(2020/2/13)
   # get 'payments/pay_select' => 'payments#construction'

   get 'payments/complete_payment' => 'payments#complete_payment'
   get 'payments/complete_cash_payment' => 'payments#complete_cash_payment'
   get 'payments/:id/new' => 'payments#new'
   delete 'payment_destroy/:id' => 'payments#payment_destroy'
   resources :payments, :only => [:show, :index, :edit, :update, :destroy]
   resources :page_contents
   
#   算命学用
   get 'sanmeis/menu' => 'sanmeis#menu'
   get 'sanmeis/meishiki' => 'sanmeis#meishiki'
   get 'sanmeis/enegry' => 'sanmeis#energy'
   get 'sanmeis/handred_hyou' => 'sanmeis#handred_hyou'
   get 'sanmeis/handred_graph' => 'sanmeis#handred_graph'
   get 'sanmeis/koudo_area' => 'sanmeis#koudo_area' 
   get 'sanmeis/rikushin' => 'sanmeis#rikushin'

   # 新予約システム 2025/08/01
   # ✅ 新予約機能
   resources :new_reserves, except: [:edit, :update] do
      collection do
       post :confirm
      end
   end

   get 'calendar', to: 'calendar#index'
   get 'calendar/availability', to: 'calendar#availability', defaults: { format: :json }

   namespace :admin do
      resources :new_schedules, only: [:index, :create, :update, :destroy]
      resources :new_reserves, only: [:index, :show, :destroy]
      # 出張登録管理
      resources :business_trips, only: [:index, :create, :destroy] do
         collection do
         patch :bulk_update
         end
      end 
   end

     # スタッフスケジュール管理
   resources :new_staff_schedules, only: [:index, :show, :update] do
      collection do
      patch :bulk_update
      end
   end

   # 旧パスから新パスへのリダイレクト
   get 'staff_schedules', to: redirect('/new_staff_schedules')

    

   

   
   
   resources :meishikis, only: [:new, :create, :index, :show, :destroy]

   get '*anything' => 'errors#routing_error'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  layout 'main/main'
  
  def top
  end
  
  def readme
    @user = User.find(current_user.id)
  end
  
  def readmust
    @page_id = params[:id]
    if @page_id == "1"
      redirect_to root_path
    end
    @user = User.find_by(id: current_user.id)
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_readme_10.html.erb
<h3 class="construction">建設中！！</h3>

app/views/home/_readme_2.html.erb
     <% text = 
     PageContent.find_by(id: 2).content
# "必ずお読みください

# mStarCOSMICをご利用ありがとうございます。

# 前日、当日キャンセルは現金もしくは、振込にて全額お支払いして頂きますのでご了承下さい

# ☆セラピー料金
# 初めての方 10000円
# ２回目以降   9000円

# ☆お得な回数券(11枚)
# 87000円
# ご家族で使用OK、転売不可
# 発行より２年間有効
# ・紹介料キャッシュバック併用不可
# ・スタンプカードは本人の分のみ
# ・不使用回数を返金することはできません

# ☆集中的に受けたい方
# 30000円
# 初日から１ヶ月間有効→5回まで
# ・不使用回数を返金することはできません
# ・紹介料キャッシュバック併用不可
# ・スタンプカード併用不可


# ☆５人以上の場合は出張も致します
# 交通費往復+出張費を頂いています
# 出張費は、下記のどれか該当するものになります
# ①片道30分以内3000円
# ②片道60分以内4000円
# ③片道90分以内5000円
# ④片道90分以上10000円
# ⑤４人以下5000円
# 宿泊の場合は宿泊費も頂いております
# ・スタンプカード、回数券併用不可
# ・出張キャンセルは１週間前までにお願いします
# ・それ以降は人数分の全額を頂いております

# ・動けない状態の方など、特別な場合はご相談ください
# １人でも出張費5000円〜10000円（距離）＋交通費で伺います。"
%>
  <%= simple_format(text) %>
  

app/views/home/_readme_3.html.erb
     <% text = 
     PageContent.find_by(id: 3).content
# "必ずお読みください

# mStarCOSMICをご利用ありがとうございます。

# 前日、当日キャンセルは現金もしくは、振込にて全額お支払いして頂きますのでご了承下さい

# ☆セラピー料金
# 初めての方 12000円
# ２回目以降 10000円

# ☆お得な回数券(11枚)
# 100000円
# ご家族で使用OK、転売不可
# 発行より２年間有効
# ・紹介料キャッシュバック併用不可
# ・スタンプカードは本人の分のみ
# ・不使用回数を返金することはできません

# ☆集中的に受けたい方
# 35 000円
# 初日から１ヶ月間有効→5回まで
# ・不使用回数を返金することはできません
# ・紹介料キャッシュバック併用不可
# ・スタンプカード併用不可


# ☆５人以上の場合は出張も致します
# 交通費往復+出張費を頂いています
# 出張費は、下記のどれか該当するものになります
# ①片道30分以内4000円
# ②片道60分以内5000円
# ③片道90分以内6000円
# ④片道90分以上10000円
# ⑤４人以下5000円
# 宿泊の場合は宿泊費も頂いております
# ・スタンプカード、回数券併用不可
# ・出張キャンセルは１週間前までにお願いします
# ・それ以降は人数分の全額を頂いております

# ・動けない状態の方など、特別な場合はご相談ください
# １人でも出張費10000円〜15000円(上記距離による)＋交通費で伺います。"
%>
  <%= simple_format(text) %>
  

app/views/home/_readme_4.html.erb
     <% text = "

必ずお読みください

mStarCOSMICをご利用ありがとうございます。

前日、当日キャンセルは現金もしくは、振込にて全額お支払いして頂きますのでご了承下さい。

☆セラピー料金
初めての方  22000円
２回目以降  20000円

お得な回数券はお問合せください

出張も致します
交通費往復+出張費を頂いています
出張費はお一人10000円頂いています
宿泊の場合は宿泊費も頂いております

※出張キャンセルは１週間前までにお願いします
それ以降は人数分の全額を頂いております。"%>
  <%= simple_format(text) %>
  

app/views/home/_readme_5.html.erb
<h3 class="construction">建設中！！</h3>

app/views/home/_readme_6.html.erb
<h3 class="construction">建設中！！</h3>

app/views/home/_readme_7.html.erb
     <% text = "


mStarCOSMICをご利用ありがとうございます。
当日500ml以上のペットボトルかナルゲンボトルを口をつけてない綺麗な状態でお持ちください。
前日、当日キャンセルは現金もしくは、振込にて全額お支払いして頂きますのでご了承下さい。

セラピー料金
代理店の方にお問い合わせお願いします。

お得な回数券もございます。
（5枚、11枚があります）

出張も致します。
交通費往復+出張費を頂いています。
出張費はお一人10000円頂いています。
宿泊の場合は宿泊費も頂いております。

(出張キャンセルは１週間前までにお願いします。それ以降は人数分の全額を頂いております）"%>
  <%= simple_format(text) %>
  

app/views/home/_readme_8.html.erb
<h3 class="construction">建設中！！</h3>

app/views/home/_readme_9.html.erb
<h3 class="construction">建設中！！</h3>

app/views/home/_readme_error.html.erb
<h3 class="construction">建設中！！！</h3>

app/views/home/lppage.html.erb
<div class="lppage-top">
</div>

<div id="page_top"><a href="#"></a></div>

<div class="container lppage-main">
    <p class="size-h2">こんな方に是非おすすめです！！</p>
    <p class="size-h3">・施術中に予約の電話が鳴って困る</p>
    　　<p class="size-p">⇨　お客様が予約カレンダーを見ながら予約できる。</p>
    　　<p class="size-p">⇨　施術中も予約を受付できる。</p>
    <div class="lppage-img">
        <img src="img/reservation-window-2.png">
    </div>　　　
    　　<p class="size-p">⇨　過去の予約も全て管理できる。</p>
    　　<p class="size-p">⇨　カレンダーをみれば予約状況（誰がいつ）が一目でわかる。</p>
    <div class="lppage-img">
        <img src="img/admin-reseve-info.png">
    </div>　　
    　　
    <p class="size-h3">・お客様情報をノートやエクセルで管理している。</p>
    　　<p class="size-p">⇨　全会員情報が一覧で見れる。</p>
    　　<p class="size-p">⇨　名前等で検索できる。</p>
    　　<p class="size-p">⇨　会員レベルを修正できる。</p>
    <div class="lppage-img">
        <img src="img/member-index.png">
    </div>　　
    <p class="size-h3">・カード決済も導入したい</p>
　　<p class="size-p">⇨　Paypalを使っているのでクレジットカード情報非保持化に準拠している。</p>
　　<p class="size-p">⇨　カードセキュリティがしっかりしている。</p>    
    <div class="lppage-img">
        <img src="img/paypal.png">
    </div>
    <p class="size-h3">・お問合せの管理がちゃんとできていない。</p>
    　　<p class="size-p">⇨　お問合せをデータベースに保存・管理（受信・一覧・回答等）。</p>
    <p class="size-h3">・会員レベルを設けてレベルごとに金額を変えたい。</p>
    　　<p class="size-p">⇨　例：一般会員・特別会員　など制限なく会員レベルを設定できて。</p>
    　　　　<p class="size-p">それぞれ違う金額を設定出来ます。</p>
    <p class="size-h3">・回数券を発行したいが、管理が難しいから実施できていない。</p>
    　　<p class="size-p">⇨　例：10回チケットを発行して、施術後に消し込みできる。</p>
    <div class="lppage-img">
        <img src="img/coupon-process.png">
    </div>
    <div class="bottom"></div>
    <div class="hpcm-inquiry-btn">
        <%= link_to "HP制作についてのお問合せはこちら--->", new_inquiry_path, class: "btn-inquiry-hpcm" %>
    </div> 　　
</div>

app/views/home/readme.html.erb
<div class="container">
<!--<h3>必ずお読みください</h3>-->

 <div class="readme">      
        <% case @user.user_type.to_i  %>
        <% when 2 then %>
        <%= render :partial => "readme_2"  %>
        <% when 3 then %>
        <%= render :partial => "readme_3"  %>
        <% when 4 then %>
        <%= render :partial => "readme_4"  %>
        <% when 5 then %>
        <%= render :partial => "readme_5"  %>
        <% when 6 then %>
        <%= render :partial => "readme_6"  %>
        <% when 7 then %>
        <%= render :partial => "readme_7"  %>
        <% when 8 then %>
        <%= render :partial => "readme_8"  %>
        <% when 9 then %>
        <%= render :partial => "readme_9"  %>
        <% when 10 then %>
        <%= render :partial => "readme_10"  %>
        <% else %>
        <%= render :partial => "readme_error"  %>
        <% end %>
        
  </div>  

</div>


  <!--{:id => 1, :type_name => "管理者", :price => 0 },-->
  <!--{:id => 2, :type_name => "既存＆distributor", :price => 9000 },-->
  <!--{:id => 3, :type_name => "新規&一般",         :price => 10000 },-->
  <!--{:id => 4, :type_name => "病人(5回券/月)",    :price => 30000 },-->
  <!--{:id => 5, :type_name => "既存＆distributorの回数券(11枚)", :price => 87000 },-->
  <!--{:id => 6, :type_name => "新規&一般の回数券(11枚)", :price => 97000 },-->
  <!--{:id => 7, :type_name => "代理店", :price => 9000 },-->
  <!--{:id => 8, :type_name => "代理店の回数券(11枚)", :price => 9000 },-->
  <!--{:id => 9, :type_name => "その他", :price => 9000 },-->
  <!--{:id => 10, :type_name => "特別ユーザー", :price => 0 }-->

app/views/home/readmust.html.erb
<div class="container">

<% if admin_user? %>
    <% if PageContent.find_by(id: @page_id.to_i) %>
      <% text = PageContent.find_by(id: @page_id.to_i).content %>
      <%= simple_format(text) %> 
    <% else %>
      <h3 class="construction">建設中！！</h3>
    <% end %>
    <!--< PageContent.all.each do |pc| %>-->
    <!--  <h3>< pc.area %></h3>-->
    <!--  < simple_format(pc.content) %>-->
    <!--  <hr>-->
    <!--< end %>-->
<% else %>
    <% if PageContent.find_by(user_type_id: @user.user_type.to_i) %>
      <% text = PageContent.find_by(user_type_id: @user.user_type.to_i).content %>
      <%= simple_format(text) %> 
    <% else %>
      <h3 class="construction">建設中！！</h3>
    <% end %>
<% end %>

</div>

app/views/home/top.html.erb
<!--header-->
<div class="header-image">
  <div class="container text-center">
    <h1 class="text-main">m☆COSMIC</h1>
    <br>
    <% if !user_signed_in? %> 
    
      <%= link_to "無料登録", new_user_registration_path, class:"singup btn btn-info" %>
      <%= link_to "ログイン", new_user_session_path, class:"singin btn btn-success" %>
    <% end %>
  </div>
</div>

<!--func-->

<div class="top-comment flex-box">
  <div>
      <p class="title">m☆COSMIC</p>
  </div>
  <div class="item">
     <% text = PageContent.find_by(id: 1).content %>
     <%= simple_format(text) %>
  </div>
</div>

    
    
    
</div>



<!--footer-->


 