config/routes.rb
Rails.application.routes.draw do
  get "business_trips/index"
  get "calendar/index"
  get "new_staff_schedules/index"
  get "new_schedules/index"
  get "new_reserves/index"
  get "new_reserves/show"
  get "new_reserves/confirm"
  get "new_reserves/new"

  
   #  新レイアウト用
   root "main#top"
   # root "main#top_mente"
   get "about_metatron" => "main#about_metatron"
   get "intestinal" => "main#intestinal"
   get "price_plan" => "main#price_plan"
   get "price_plan_coupon" => "main#price_plan_coupon"
   get "fasting" => "main#fasting"
   get "intestinal" => "main#intestinal"
   get "massage" => "main#massage"
   get "registration_thanks" => "main#registration_thanks"
   get "metatron_sale" => "main#metatron_sale"
   get "staffs" => "main#staffs"
   get 'price_list_select' => 'main#price_list_select'
   get 'price_plan_admin' => 'main#price_plan_admin'

   get "special_treatment_price" => "main#special_treatment_price"

    get 'home/readme' => 'home#readme'
    get 'home/readmust/:id' => 'home#readmust'
    get 'lppage' => 'home#lppage'
    
    
    devise_for :users, :controllers => {
        :registrations => 'users/registrations',
        :sessions => 'users/sessions',
        :passwords => 'users/passwords'
    }
   
#   delete 'users/destroy_user' => 'users#destroy_user'
   resources :users, :only => [:index, :edit, :update, :show, :destroy] do
      get 'schedules/month_select' => 'schedules#month_select'
      # resources :schedules
   end
   # 全userデータバックアップ
   get 'backup_users' => 'users#backup_users'
   get 'users/index/:per' => 'users#index'
   # post 'reservations/make_holiday/:date/:space' => 'reservations#make_holiday'
   # get 'reservations/my_reserved' => 'reservations#my_reserved'
   # get 'reservations/my_reserved_past' => 'reservations#my_reserved_past'
   
   # reservations でアクセスされても新予約画面(reserves#index)へ
   # get 'reservations' => 'reserves#index'
   # resources :reservations
   
   get 'data_conversion' => 'reserves#data_conversion'
   post 'reserves/make_holiday/:date/:start_date/:space' => 'reserves#make_holiday'
   get 'reserves/my_reserved' => 'reserves#my_reserved'
   # 休日の削除
   delete 'reserves/:id/:calender_start_date/holiday' => 'reserves#delete'
   # 予約の削除
   delete 'reserves/:id' => 'reserves#destroy'
   get 'reserves/machine_select' => 'reserves#machine_select'
   get 'reserves/:machine/index' => 'reserves#index'
   get 'reserves/new_cust' => 'reserves#new_cust'
   get 'reserves/new_cust_other' => 'reserves#new_cust_other'
   
   resources :reserves, except: [:show, :destroy]
   
   get 'all_schedules' => 'schedules#all_schedules'
   
   patch "admin/staffs/staff_machine_relations" => "staff_machine_relations#update"

   
   scope :admin do
      post "/staffs/:id" => "staffs#fire"
      resources :staffs do
         resources :schedules
      end
   end
   
   
   scope :admin do
      resources :machines do
         resources :machine_schedules
      end
   end   
   
   patch "staffs/:id/nonactivate" => "staffs#nonactivate"
   patch "staffs/:id/activate" => "staffs#activate"
   
   resources :user_types
   # post 'reservations/confirm' => 'reservations#confirm'
   
   # get 'inquiries/:id/answer' => 'inquiries#answer'
   # get 'inquiries/new' => 'inquiries#new1'
   resources :inquiries do 
      resources :answers, :only => [:new, :create, :show]
   end
   
   resources :metatron_sale_inquiries do 
      resources :ms_inquiry_answers, :only => [:new, :create, :show]
   end   
   
   # get 'answers/:id/new' => 'answers#new'
   # resources :answers, :only => [:create, :show, :index]
   
   resources :pay_types
   

   get 'payments/pay_select' => 'payments#pay_select'
   #　上記工事中にて下記に(2020/2/13)
   # get 'payments/pay_select' => 'payments#construction'

   get 'payments/complete_payment' => 'payments#complete_payment'
   get 'payments/complete_cash_payment' => 'payments#complete_cash_payment'
   get 'payments/:id/new' => 'payments#new'
   delete 'payment_destroy/:id' => 'payments#payment_destroy'
   resources :payments, :only => [:show, :index, :edit, :update, :destroy]
   resources :page_contents
   
#   算命学用
   get 'sanmeis/menu' => 'sanmeis#menu'
   get 'sanmeis/meishiki' => 'sanmeis#meishiki'
   get 'sanmeis/enegry' => 'sanmeis#energy'
   get 'sanmeis/handred_hyou' => 'sanmeis#handred_hyou'
   get 'sanmeis/handred_graph' => 'sanmeis#handred_graph'
   get 'sanmeis/koudo_area' => 'sanmeis#koudo_area' 
   get 'sanmeis/rikushin' => 'sanmeis#rikushin'

   # 新予約システム 2025/08/01
   # ✅ 新予約機能
   resources :new_reserves, except: [:edit, :update] do
      collection do
       post :confirm
      end
   end

   get 'calendar', to: 'calendar#index'
   get 'calendar/availability', to: 'calendar#availability', defaults: { format: :json }

   namespace :admin do
      resources :new_schedules, only: [:index, :create, :update, :destroy]
      resources :new_reserves, only: [:index, :show, :destroy]
      # 出張登録管理
      resources :business_trips, only: [:index, :create, :destroy] do
         collection do
         patch :bulk_update
         end
      end 
   end

     # スタッフスケジュール管理
   resources :new_staff_schedules, only: [:index, :show, :update] do
      collection do
      patch :bulk_update
      end
   end

   # 旧パスから新パスへのリダイレクト
   get 'staff_schedules', to: redirect('/new_staff_schedules')

    

   

   
   
   resources :meishikis, only: [:new, :create, :index, :show, :destroy]

   get '*anything' => 'errors#routing_error'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
    has_many :coupons, :dependent => :destroy
    belongs_to :user
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  
  layout 'main/main'
  
  before_action :authenticate_user!
  before_action :authenticate_admin_user?, only: [:index]
  before_action :access_controll_payment, only: [:show, :edit, :update, :destroy]
  # before_action :payment_valid, only: [:complete_cash_payment, :complete_payment]
  
  def pay_select
    # @user_type = User.find_by(id: current_user.id).user_type
    @payments = current_user.payments
  end 
  
  def construction
  end
  
  # pay_select.html.erb　からくる
  def new
    @number_of_coupons = params[:id]
    session[:number_of_coupons] = @number_of_coupons
    logger.debug("============================= @number_of_coupons = #{@number_of_coupons}")
    @user = User.find_by(id: current_user.id)
    @payment = Payment.new
  end
  
  
  
  def complete_cash_payment
    @number_of_coupons = session[:number_of_coupons]
    logger.debug("============================= complete_cash_payment number_of_coupons = #{@number_of_coupons}")
    @user = User.find(current_user.id)
    # price = PayType.find(@pay_type).price
    # @payment = Payment.new(user_id: current_user.id, price: price, pay_type: @pay_type)
    @payment = Payment.new(user_id: current_user.id)
    if @payment.save
      # 回数券の人のレコード作成
      # coupon_times(@number_of_coupons).times do |i|
      @number_of_coupons.to_i.times do |i|
        Coupon.create(payment_id: @payment.id, status: "new", order_number: i+1)
             logger.debug("============================= coupon no = #{i+1}")
      end
      # if [4,5,6,8,11].include?(@pay_type)
      # 2024/6/19 回数券は5,10回のみにした
      # if [5,10].include?(@number_of_coupons)
        flash[:notice] = "現金支払い処理完了・回数券発行しました"
      # else 
        # flash[:notice] = "現金支払い処理完しました"
      # end        
      session[:pay_type] = nil
      redirect_to payment_path(@payment)
    else
      flash[:notice] = "支払い処理に失敗しました"
      session[:pay_type] = nil
      redirect_back(fallback_location: root_path)
    end
  end
  

  
  def complete_payment
    @pay_type = session[:pay_type]
    @user = User.find(current_user.id)
    price = PayType.find(@pay_type).price
    @payment = Payment.new(user_id: current_user.id, price: price, pay_type: @pay_type)
    if @payment.save
      # 回数券の人のレコード作成
      coupon_times(@pay_type).times do |i|
        Coupon.create(payment_id: @payment.id, status: "new", order_number: i+1)
             logger.debug("============================= credit coupon no = #{i+1}")
      end
      if [4,5,6,8,11].include?(@pay_type)
        flash[:notice] = "クレジット支払い処理完了・回数券発行しました"
      else 
        flash[:notice] = "クレジット支払い処理完了しました"
      end
      session[:pay_type] = nil
      redirect_to payment_path(@payment)
    else
      flash[:notice] = "支払い処理に失敗しました"
      session[:pay_type] = nil
      redirect_back(fallback_location: root_path)
    end
  end
  
  def index
    if current_user.user_type == "1"
      # 全ユーザーの支払い履歴一覧
      @payments = Payment.all.order(created_at: :desc)
    else
      @payments = Payment.where(user_id: current_user.id).order(created_at: :desc)
    end

  end
  
  def show
    @payment = Payment.find(params[:id])
    @user = User.find(@payment.user_id)
  end
  
  def edit
    # あるユーザーのある支払いに対してのedit
    @payment = Payment.find(params[:id])
    @user = User.find(@payment.user_id)
    @used_coupons = Coupon.where(payment_id: @payment.id, status: "used")
    @new_coupons = Coupon.where(payment_id: @payment.id, status: "new")
  end 
  
  def update
    @payment = Payment.find(params[:id])
    if @coupon = Coupon.find_by(payment_id: @payment.id, status: "new") # 未使用のレコード１件取得
          @coupon.status = "used"
          @coupon.remarks = params[:payment][:remarks]
          if @coupon.save
            flash[:notice] = "回数券を１枚使用しました"
            redirect_to "/payments/#{@payment.id}/edit"
          else
            flash[:notice] = "回数券を使用できませんでした"
            redirect_back(fallback_location: root_path)
          end
    else
       flash[:notice] = "未使用の回数券はありません"
       redirect_back(fallback_location: root_path)
    end
  end
  
  # couponを一枚ずつ削除する機能
  def destroy
    @payment = Payment.find(params[:id])
    @coupon = Coupon.where(payment_id: @payment.id, status: "used").order(updated_at: :asc).last
    @coupon.status = "new"
    if @coupon.save
      flash[:notice] = "取消しました"
      redirect_to "/payments/#{@payment.id}/edit"
    else
      flash[:notice] = "取消せませんでした"
      redirect_back(fallback_location: root_path)
    end
  end
  
  # payment.coupon情報削除　管理者のみ実行可能
  def payment_destroy
    @payment = Payment.find(params[:id])
    @payment.destroy
    
    if @payment.destroy
      flash[:notice] = "回数券を削除しました"
      redirect_to payments_path
    else
      flash[:notice] = "支払情報を削除できませんでした"
      render "payments/index"
    end
  end
  
  
  
  
  private 
     def payment_params
        params.require(:payment).permit(:user_id, :price, :remarks, :user_type).merge(user_id: current_user.id, user_type: User.find(current_user.id).user_type)
     end
     
     def coupon_times(pay_type)
        coupon_times = 0
        case pay_type.to_i
        when 5,9,13,17 then   # 病人(5回券/月)
          coupon_times = 5
        when 4,8,12,16,99 then   # 既存＆distributorの回数券(11枚)
          coupon_times = 11
        else
          coupon_times = 0
        end 
      
        return coupon_times
     end
     
     def access_controll_payment
       if !Payment.find_by(id: params[:id])
         flash[:alert] = "指定の支払い情報が存在しません"
         redirect_to payments_path
       end
     end
     
     def payment_valid
       logger.debug("^^^^^^^^^^^^^^^^^^^^^ payment_valid session = #{session[:pay_type]}")
       @user = User.find_by(id: current_user.id)
       
       flag = false
       
       case @user.user_type.to_i
        when 1 then   # 管理者は全てok
            flag = true
        when 2 then   # 会員
          case session[:pay_type].to_i
          when 2,3,4,5 then
            flag = true
          else
            flag = false
          end
        when 3 then   # 一般
          case session[:pay_type].to_i
          when 6,7,8,9 then
            flag = true
          else
            flag = false
          end 
        when 4 then   # 代理店A
          case session[:pay_type].to_i
          when 10,11,12,13 then
            flag = true
          else
            flag = false
          end 
        when 5 then   # 代理店B
          case session[:pay_type].to_i
          when 14,15,16,17 then
            flag = true
          else
            flag = false
          end 
        when 6 then   # 特別会員
          case session[:pay_type].to_i
          when 18 then
            flag = true
          else
            flag = false
          end 
        when 7 then   # その他
          case session[:pay_type].to_i
          when 19 then
            flag = true
          else
            flag = false
          end 
        when 99 then   # テスト
          case session[:pay_type].to_i
          when 99 then
            flag = true
          else
            flag = false
          end          
        else
          flag = false
        end 
        
        logger.debug("~~~~~^^^^^^^^^^^^^ flag = #{flag}")
       
         if !flag
           flash[:alert] = "支払いタイプに不整合が起こりました"
           redirect_to "/payments/pay_select"
         end
     end
     
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_new_11.html.erb
<!-- 新規・一般／病人(5回券/月) 35000円-->
<div>
  <hr>
    <p>クレジット支払い</p>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
      <input type="hidden" name="cmd" value="_s-xclick">
      <input type="hidden" name="hosted_button_id" value="2FTBPU5555U5L">
      <input type="image" src="https://www.paypalobjects.com/ja_JP/JP/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - オンラインでより安全・簡単にお支払い">
      <img alt="" border="0" src="https://www.paypalobjects.com/ja_JP/i/scr/pixel.gif" width="1" height="1">
    </form>

    <hr>
    <%= link_to "現金払い", payments_complete_cash_payment_path, :class => "btn btn-primary" %>    
</div>

app/views/payments/_new_12.html.erb
<!-- 代理店の回数券(5枚) 87000円　-->
<div>
  <hr>
    <p>クレジット支払い</p>
        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="QKHZCBB78K9NE">
            <input type="image" src="https://www.paypalobjects.com/ja_JP/JP/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - オンラインでより安全・簡単にお支払い">
            <img alt="" border="0" src="https://www.paypalobjects.com/ja_JP/i/scr/pixel.gif" width="1" height="1">
        </form>

    <hr>
    <%= link_to "現金払い", payments_complete_cash_payment_path, :class => "btn btn-primary" %>    
</div>

app/views/payments/_new_2.html.erb
<!-- 既存＆distributor 9000円 -->
<div>
  <hr>
    <p>クレジット支払い</p>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
      <input type="hidden" name="cmd" value="_s-xclick">
      <input type="hidden" name="hosted_button_id" value="WRPBH6YRSQTKN">
      <input type="image" src="https://www.paypalobjects.com/ja_JP/JP/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - オンラインでより安全・簡単にお支払い">
      <img alt="" border="0" src="https://www.paypalobjects.com/ja_JP/i/scr/pixel.gif" width="1" height="1">
    </form>

    <hr>
    <%= render 'payments/_cach' %>
    <%= link_to "現金払い", payments_complete_cash_payment_path, :class => "btn btn-primary" %>    
</div>

app/views/payments/_new_4.html.erb
<!-- 既存＆distributor　病人(5回券/月)　30000-->
<div>
  <hr>
    <p>クレジット支払い</p>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
      <input type="hidden" name="cmd" value="_s-xclick">
      <input type="hidden" name="hosted_button_id" value="594PREZS3KEXE">
      <input type="image" src="https://www.paypalobjects.com/ja_JP/JP/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - オンラインでより安全・簡単にお支払い">
      <img alt="" border="0" src="https://www.paypalobjects.com/ja_JP/i/scr/pixel.gif" width="1" height="1">
    </form>

    <hr>
    
    <%= link_to "現金払い", payments_complete_cash_payment_path, :class => "btn btn-primary" %>    
    ddfddf
</div>

app/views/payments/_new_5.html.erb
<!-- 既存＆distributorの回数券(11枚) 87000-->
<div>
  <hr>
    <p>クレジット支払い</p>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
      <input type="hidden" name="cmd" value="_s-xclick">
      <input type="hidden" name="hosted_button_id" value="HTJTB45ETH5TW">
      <input type="image" src="https://www.paypalobjects.com/ja_JP/JP/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - オンラインでより安全・簡単にお支払い">
      <img alt="" border="0" src="https://www.paypalobjects.com/ja_JP/i/scr/pixel.gif" width="1" height="1">
    </form>
    <hr>
    <%= link_to "現金払い", payments_complete_cash_payment_path, :class => "btn btn-primary" %>    


</div>

app/views/payments/_new_8.html.erb
<!-- 代理店の回数券(11枚)　180000-->
<div>
  <hr>
    <p>クレジット支払い</p>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="hosted_button_id" value="GDUYXUT75D7V4">
        <input type="image" src="https://www.paypalobjects.com/ja_JP/JP/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - オンラインでより安全・簡単にお支払い">
        <img alt="" border="0" src="https://www.paypalobjects.com/ja_JP/i/scr/pixel.gif" width="1" height="1">
    </form>
    <hr>
    <%= link_to "現金払い", payments_complete_cash_payment_path, :class => "btn btn-primary" %>    

</div>

app/views/payments/_new_paypal.html.erb
<div>
    <p>現在、Paypalでのクレジット支払い工事中です</p>
    <p>サロンでのカード支払いをお願いします。</p>
    <p>現金払いの方は下記ボタンをクリックしてください。</p>
</div>    
<div>     
    <hr>
        <%= render 'payments/cash' %>
</div>

app/views/payments/_test.html.erb
<!-- テスト　1円-->
<div>
  <hr>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
      <input type="hidden" name="cmd" value="_s-xclick">
      <input type="hidden" name="hosted_button_id" value="3XKANX3H3NJ8S">
      <input type="image" src="https://www.paypalobjects.com/ja_JP/JP/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - オンラインでより安全・簡単にお支払い">
      <img alt="" border="0" src="https://www.paypalobjects.com/ja_JP/i/scr/pixel.gif" width="1" height="1">
    </form>

    <hr>
    <%= link_to "現金払い", payments_complete_cash_payment_path, :class => "btn btn-primary" %>    
</div>

app/views/payments/construction.html.erb
<div class="construction">
    <h3>お支払い</h3>
    <h4>工事中にて</h4>
    <p>※サロンで現金もしくはカード決済で</p>
    <p>お支払いください。</p>
</div>
<style>

.construction {
    width: 100%;
    margin: 0 auto;
    padding: 100px 0;
}
    h4 {
      padding: 50px 0 0 0;
    }
</style>

app/views/payments/edit.html.erb
<div class="container edit">
<h3>回数券処理</h3>

<h4>会員名：<%= @user.name %></h4>
<!--<h4>会員タイプ：<= UserType.find(@user.user_type.to_i).type_name %></h4>-->
<h4>残り回数券：<%= @new_coupons.count %>枚</h4>

 <div class="container">        
    <%= form_for(@payment) do |f| %>
      <div class="field">
        <%= f.label :備考：１０文字以内 %><br />
        <%= f.text_field :remarks, :class => "col-xs-3" %><br>
      </div>
        <%= f.submit "回数券を使う", :class => "btn btn-success" %>
    <% end %>

    <h3 class="my-reserved-title">回数券一覧</h3>
    
        <table class="table table-bordered table-schedule">
          <thead>
            <tr>
              <th scope="col">回数券使用日時</th>
              <th scope="col">備考</th>
            </tr>
          </thead>
          <tbody>
            <% @used_coupons.each do |used_coupon| %>
               <tr>
                  <td><%= used_coupon.updated_at.strftime("%Y/%m/%d....%H:%M") %></td>
                  <% if used_coupon.remarks %>
                    <td><%= used_coupon.remarks %></td>
                  <% else %>
                    <td><%= "------" %></td>
                  <% end %>
               </tr>
            <% end %>
          </tbody>
        </table>
    
    <% if Coupon.find_by(payment_id: @payment.id, status: "used") %>
       <%= link_to "１枚取消", "/payments/#{@payment.id}", :method => "delete", :class => "cancel btn btn-danger" %>
    <% end %>

</div>
</dir>

app/views/payments/index.html.erb
<div class="container">
    <h2 class="my-reserved-title">お支払い一覧</h2>
    
        <table class="table table-bordered table-schedule table-striped">
          <thead>
            <tr>
              <th scope="col">開始日</th>
              <th scope="col">名前</th>
              <th scope="col">処理</th>
            </tr>
          </thead>
          <tbody>
            <% @payments.each do |payment| %>
                <%  logger.debug("------------------------------ html payment      = #{payment.id}--#{payment.pay_type}") %>
               <tr>
                  <td class="center"><%= link_to payment.created_at.strftime("%Y-%m-%d"), edit_payment_path(payment) %></td>
                  <td class="center"><%= User.find_by(id: payment.user_id).name %></td>
                  <td class="center"><%= link_to "削除", "payment_destroy/#{payment.id}", :method => "delete", data: { confirm: Global::PAY_DESTROY } %></td>
               </tr>
            <% end %>
          </tbody>
        </table>
</div>

app/views/payments/pay_select.html.erb
<h3 class="paytitle">回数券購入</h3>

<%= link_to "5回", "/payments/5/new", :class => "btn btn-primary paytype" %>
<%= link_to "10回", "/payments/10/new", :class => "btn btn-primary paytype" %>

<div class="bought-coupon">
<hr>
  <div class="title">購入済み回数券</div>
  
    
        <table class="table table-bordered table-schedule table-striped">
          <thead>
            <tr>
              <th scope="col">開始日</th>
              <th scope="col">回数</th>
              <th scope="col">使用済み</th>
              <th scope="col">残回数</th>
            </tr>
          </thead>
          <tbody>
            <% @payments.each do |payment| %>
               <tr>
                  <td class="center"><%= payment.created_at.strftime("%Y.%m.%d") %></td>
                  <td class="center"><%= payment.coupons.count %></td>
                  <td class="center">
                      <% payment.coupons.where(status: "used").order(:updated_at).each do |coupon| %>
                        <%= coupon.updated_at.strftime("%Y.%m.%d") %><br>
                      <% end %>
                  </td>
                  <td class="center"><%= payment.coupons.where(status: "new").count %></td>
               </tr>
            <% end %>
          </tbody>
        </table>  

</div>

<style>

</style>

app/views/payments/pay_select_2.html.erb
<h3 class="paytitle">支払い方法選択</h3>

<% case @user_type.to_i %>
<% when 1 then   # 管理者テスト期間中のみ %>  
    <p class="test">-----   会員  -----</p>
        <% PayType.where(user_type_id: 2).each do |p| %>
          <%= link_to "#{number_with_delimiter(p.price)}円　#{p.pay_name}", "/payments/#{p.id}/new", :class => "btn btn-primary paytype" %>
        <% end %>
    <p class="test">-----   一般  -----</p>
        <% PayType.where(user_type_id: 3).each do |p| %>
          <%= link_to "#{number_with_delimiter(p.price)}円　#{p.pay_name}", "/payments/#{p.id}/new", :class => "btn btn-primary paytype" %>
        <% end %>
    <p class="test">-----   代理店A  -----</p>
        <% PayType.where(user_type_id: 4).each do |p| %>
          <%= link_to "#{number_with_delimiter(p.price)}円　#{p.pay_name}", "/payments/#{p.id}/new", :class => "btn btn-primary paytype" %>
        <% end %>
    <p class="test">-----   代理店B  -----</p>
        <% PayType.where(user_type_id: 5).each do |p| %>
          <%= link_to "#{number_with_delimiter(p.price)}円　#{p.pay_name}", "/payments/#{p.id}/new", :class => "btn btn-primary paytype" %>
        <% end %>
    <p class="test">-----    特別会員 -----</p>
        <% PayType.where(user_type_id: 6).each do |p| %>
          <%= link_to "無料　#{p.pay_name}", "/payments/#{p.id}/new", :class => "btn btn-primary paytype" %>
        <% end %>
    <p class="test">-----    テスト  -----</p>
        <% PayType.where(user_type_id: 99).each do |p| %>
          <%= link_to "#{number_with_delimiter(p.price)}円　#{p.pay_name}", "/payments/#{p.id}/new", :class => "btn btn-primary paytype" %>
        <% end %>
    <hr>
<% when 2,3,4,5,6,7,99 then # 会員・新規・代理店A.B・特別会員・その他・テスト %>
    <% PayType.where(user_type_id: @user_type.to_i).each do |p| %>
      <%= link_to "#{number_with_delimiter(p.price)}円　#{p.pay_name}", "/payments/#{p.id}/new", :class => "btn btn-primary paytype" %>
    <% end %>
<% else %>
    <%= link_to "支払い対象外", "/payments/#{@user_type.to_i}/new", :class => "btn btn-primary paytype" %>
<% end  %>

app/views/payments/show.html.erb
<div class="container">
<h3>支払い完了</h3>

  <div class="field name">
    <p><%= @user.name %>様　お支払いありがとうございました</p>
  </div>
  
  
  <hr>
</div>